name: CD Pipeline
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: portfolio-artifact
          path: ./artifact
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Unzip artifact
        run: |
          echo "Clearing deployed directory..."
          rm -rf ~/student-portfolio-deployed
          mkdir -p ~/student-portfolio-deployed
          echo "Unzipping artifact..."
          unzip -o ./artifact/portfolio-artifact.zip -d ~/student-portfolio-deployed
          ls -la ~/student-portfolio-deployed
      - name: Install dependencies
        working-directory: ~/student-portfolio-deployed
        run: |
          echo "Installing dependencies..."
          npm install --production
          ls -la src
          ls -la public
      - name: Stop any existing server
        working-directory: ~/student-portfolio-deployed
        run: |
          echo "Stopping existing server..."
          if [ -f server.pid ]; then
            echo "Killing process from server.pid..."
            kill $(cat server.pid) 2>/dev/null || true
            rm -f server.pid
          fi
          echo "Stopping systemd service..."
          sudo systemctl stop portfolio.service 2>/dev/null || true
          echo "Checking for processes on port ${{ secrets.APP_PORT || '3000' }}..."
          lsof -i :${{ secrets.APP_PORT || '3000' }} || true
      - name: Create and start systemd service
        working-directory: ~/student-portfolio-deployed
        run: |
          echo "Creating systemd service file..."
          sudo bash -c "printf '[Unit]\nDescription=Student Portfolio Express Server\nAfter=network.target\n\n[Service]\nExecStart=/usr/bin/node $(pwd)/src/server.js\nWorkingDirectory=$(pwd)\nRestart=always\nUser=hp\nEnvironment=PORT=${{ secrets.APP_PORT || '3000' }}\n\n[Install]\nWantedBy=multi-user.target\n' > /etc/systemd/system/portfolio.service"
          echo "Reloading systemd daemon..."
          sudo systemctl daemon-reload
          echo "Enabling service..."
          sudo systemctl enable portfolio.service
          echo "Starting service..."
          sudo systemctl restart portfolio.service
          echo "Checking service status..."
          sudo systemctl status portfolio.service --no-pager
        timeout-minutes: 1
      - name: Verify server is running
        working-directory: ~/student-portfolio-deployed
        run: |
          echo "Waiting for server to start..."
          sleep 20
          echo "Checking server at http://localhost:${{ secrets.APP_PORT || '3000' }}..."
          curl -v -f http://localhost:${{ secrets.APP_PORT || '3000' }} || exit 1
          echo "Server is running successfully"
