```yaml
name: CD Pipeline
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    needs: ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: portfolio-artifact
          path: ./artifact
      - name: Unzip artifact
        run: unzip ./artifact/portfolio.zip -d ./deployed
      - name: Install dependencies
        run: npm install
        working-directory: ./deployed
      - name: Stop any existing server
        run: pkill -f "node src/server.js" || true
        working-directory: ./deployed
      - name: Start application in background
        run: nohup npm start &
        working-directory: ./deployed
        env:
          PORT: ${{ secrets.APP_PORT }}
      - name: Verify server is running
        run: |
          sleep 5
          curl -f http://localhost:${{ secrets.APP_PORT }} || exit 1
        working-directory: ./deployed
```
