name: CD Pipeline
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: portfolio-artifact
          path: ./artifact
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Unzip artifact
        run: unzip ./artifact/portfolio-artifact.zip -d ./deployed
      - name: Install dependencies
        working-directory: ./deployed
        run: npm install
      - name: Stop any existing server
        working-directory: ./deployed
        run: pkill -f "node src/server.js" || true
      - name: Start application in background
        working-directory: ./deployed
        env:
          PORT: ${{ secrets.APP_PORT }}
        run: nohup npm start &
      - name: Verify server is running
        working-directory: ./deployed
        run: |
          sleep 5
          curl -f http://localhost:${{ secrets.APP_PORT }} || exit 1
