name: CD Pipeline
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: portfolio-artifact
          path: ./artifact
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Clean deploy directory
        run: |
          echo "Cleaning deploy directory..."
          rm -rf ./deployed
          mkdir -p ./deployed
      - name: Unzip artifact
        run: |
          echo "Unzipping artifact..."
          unzip -o ./artifact/portfolio-artifact.zip -d ./deployed
          ls -la ./deployed
          echo "Checking for server.js..."
          ls -la ./deployed/src
      - name: Install dependencies
        working-directory: ./deployed
        run: |
          echo "Installing dependencies..."
          npm ci
          npm list express || echo "Express not found"
      - name: Stop any existing server
        working-directory: ./deployed
        run: |
          echo "Stopping existing server..."
          pkill -f "node.*server.js" || true
          lsof -i :3000 || true
      - name: Log runner IP address
        run: |
          echo "Runner IP address:"
          hostname -I || echo "Could not determine IP address"
          curl -s http://ifconfig.me || echo "Could not fetch public IP"
      - name: Start application in background
        working-directory: ./deployed
        env:
          PORT: 3000
        run: |
          npm start
          echo "Starting application on port 3000..."
          # nohup node src/server.js </dev/null >/deployed/nohup.out 2>&1 &
          echo $! > server.pid
          sleep 5
          cat server.pid
          echo "Server process started with PID: $(cat server.pid)"
          echo "Checking if process is running..."
          ps aux | grep node || true
          echo "Checking port 3000..."
          netstat -tulnp | grep 3000 || true
          echo "Checking nohup.out for errors..."
          cat /deployed/nohup.out || echo "nohup.out not found"
        timeout-minutes: 1
      - name: Verify server is running
        working-directory: ./deployed
        run: |
          echo "Waiting for server to start..."
          sleep 30
          echo "Checking server at http://172.26.60.61:3000"
          for i in {1..3}; do
            curl -v -f http://172.26.60.61:3000 && break || echo "Attempt $i failed, retrying..."
            sleep 5
          done
          curl -v -f http://172.26.60.61:3000 || { echo "Server verification failed"; cat /deployed/nohup.out; exit 1; }
          echo "Server is running successfully"
          echo "Access the website at http://$(hostname -I | awk '{print $1}'):3000 (if on the same network) or http://<runner-public-ip>:3000"
