```yaml
name: CD Pipeline
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: portfolio-artifact
          path: ./artifact
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Unzip artifact
        run: |
          echo "Clearing deployed directory..."
          rm -rf ./deployed
          echo "Unzipping artifact..."
          unzip -o ./artifact/portfolio-artifact.zip -d ./deployed
          ls -la ./deployed
      - name: Install dependencies
        working-directory: ./deployed
        run: |
          echo "Installing dependencies..."
          npm install
      - name: Stop any existing server
        working-directory: ./deployed
        run: |
          echo "Stopping existing server..."
          if [ -f server.pid ]; then
            kill $(cat server.pid) 2>/dev/null || true
            rm -f server.pid
          fi
          lsof -i :${{ secrets.APP_PORT || '3000' }} || true
      - name: Start application in background
        working-directory: ./deployed
        env:
          PORT: ${{ secrets.APP_PORT || '3000' }}
        run: |
          echo "Starting application on port ${PORT}..."
          nohup node src/server.js > server.log 2>&1 &
          echo $! > server.pid
          echo "Server PID: $(cat server.pid)"
        timeout-minutes: 1
      - name: Verify server is running
        working-directory: ./deployed
        run: |
          echo "Waiting for server to start..."
          sleep 15
          echo "Checking server at http://localhost:${{ secrets.APP_PORT || '3000' }}"
          curl -v -f http://localhost:${{ secrets.APP_PORT || '3000' }} || exit 1
          echo "Server is running successfully"
```
