name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Build project
        run: npm run build

      - name: Zip artifact
        run: zip -r portfolio-artifact.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: portfolio-artifact
          path: portfolio-artifact.zip
